name: End-to-end tests 🧪
on:
  # manual button click form the GitHUb UI
  workflow_dispatch:
  # pushing commits to the main branch
  push:
    branches:
      - main
    # tests run every afternom
  schedule:
    - cron: '20 16 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Install NOM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
